# -*- coding: utf-8 -*-
from . import venue_room
from . import res_partner
from . import commercial_job_master
from . import commercial_job
from . import commercial_job_gate
from . import commercial_job_crew
from . import commercial_event_job
from . import commercial_checklist_template
from . import commercial_event_job_checklist
from . import commercial_scope_change
from . import commercial_event_feedback
from . import commercial_job_dashboard
from . import crm_stage
from . import crm_lead
from . import sale_order
from . import action_centre_item_tag
from . import action_centre_trigger_config
from . import action_centre_mixin
from . import action_centre_item
