v = env.ref("web.login_layout")
print("=== web.login_layout arch ===")
print(v.arch)
print()
print("=== combined arch (post-inherit) ===")
print(v.with_context(check_view_ids=v.ids).get_combined_arch())
print()
print("=== web.login arch ===")
v2 = env.ref("web.login")
print(v2.arch)
